spring.application.name=Hotel_Management_System_SWP

# 1. C?u h\uFFFDnh k?t n?i SQL Server (Thay ??i th\uFFFDng tin cho ?\uFFFDng v?i m\uFFFDy c?a b?n)
spring.datasource.url=jdbc:postgresql://localhost:5432/hms_db
spring.datasource.username=postgres
spring.datasource.password=1

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9999
spring.messages.basename=messages
spring.messages.encoding=UTF-8

## C\u1EA5u h\u00ECnh JWT (Th\u1EDDi h\u1EA1n m\u00E3 token n\u00E0y l\u00E0 1 ng\u00E0y = 86400000 ms)
#hms.jwt.secret=${HMS_JWT_SECRET}
#hms.jwt.expiration=86400000

# Pagination config
app.pagination.default-page=1
app.pagination.default-size=10
app.pagination.max-size=100

#cloud_name=dkkd1nhqr
## application.properties
#
## S? d?ng bi?n môi tr??ng, n?u không có thì l?y giá tr? sau d?u hai ch?m (optional)
#api_key=${API_KEY}
#api_secret=${API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
management.health.mail.enabled=false

spring.jpa.open-in-view=false
cloudinary.api-key=812182536878189
cloudinary.api-secret=2p2Kchn5hwo3mxqcBB46eyr9OX4
cloudinary.cloud-name=dkkd1nhqr
# C?u hình JWT (Th?i h?n mã token này là 1 ngày = 86400000 ms)
# THAY TH? BI?N ${HMS_JWT_SECRET} B?NG CHU?I SECRET C?A B?N:
hms.jwt.secret=ChonMotChuoiThatDaiVaBiMatDeLamJWTSecretKeyChoDuAnSWP391
hms.jwt.expiration=86400000


cloud_name=dkkd1nhqr
api_key=812182536878189
api_secret=2p2Kchn5hwo3mxqcBB46eyr9OX4
# ============================================
# Cau hinh luu anh vao local (thay Cloudinary)
# ============================================
app.upload.dir=uploads
app.base-url=http://localhost:9999
