spring.application.name=Hotel_Management_System_SWP

# 1. C?u h\uFFFDnh k?t n?i SQL Server (Thay ??i th\uFFFDng tin cho ?\uFFFDng v?i m\uFFFDy c?a b?n)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HMS_DB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234

# 2. C?u h\uFFFDnh c? ch? t? ??ng sinh b?ng t? Entity Java v\uFFFDo Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 3. T?t b? nh? ??m c?a Thymeleaf ?? Spring Boot DevTools c?p nh?t giao di?n ngay l?p t?c khi b?n nh?n F5
spring.thymeleaf.cache=false

server.port=9999
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# C\u1EA5u h\u00ECnh JWT (Th\u1EDDi h\u1EA1n m\u00E3 token n\u00E0y l\u00E0 1 ng\u00E0y = 86400000 ms)
hms.jwt.secret=ChonMotChuoiThatDaiVaBiMatDeBaoMatHeThongKhachSanHMS2026
hms.jwt.expiration=86400000
